# Generated by Django 4.2.3 on 2023-09-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Principal', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sname', models.CharField(max_length=100)),
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('CNName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college')),
            ],
        ),
    ]
